server:
  port: 8081

paginacao:
  qtd_por_pagina: 25

spring:
  application:
    name: 'post'
  data:
    mongodb:
      database: kotlin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka